
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - amazonwebservices.aws-toolkit-vscode
    - redhat.ansible
    - shakram02.bash-beautify
    - dbaeumer.vscode-eslint
    - hashicorp.terraform
    - christian-kohler.npm-intellisense
    - ms-python.python
    - ms-python.vscode-pylance
    - christian-kohler.path-intellisense
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - DavidAnson.vscode-markdownlint
    - ms-azuretools.vscode-docker
    - rogalmic.bash-debug
    - redhat.vscode-yaml



tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT


